##from turtle import *
##
##color("black","red")
##speed(1)
##
##pencolor("white")
##goto(-100,-100)
##pencolor("black")
##goto(-100,100)
##goto(100,100)
##goto(100,-100)
##goto(-100,-100)
##goto(0,-100)
##left(90)
##pencolor("white")
##goto(0,-10)
##pencolor("black")
##begin_fill()
##circle(10)
##end_fill()
##left(90)
##pencolor("white")
##goto(-60,-10)
##right(90)
##pencolor("black")
##begin_fill()
##circle(10)
##end_fill()
##pencolor("white")
##goto(60,-10)
##pencolor("black")
##begin_fill()
##circle(10)
##end_fill()
##
##hideturtle()
##done()
##
##

##计算长方形的面积并输出结果
a,b,s=6,3,0
##a为正方形的长，b为正方形的宽，s为正方形的面积
s=a*b
##面积公式
print("长方形的面积为:",s)
##打印出面积

